import type { NextConfig } from "next";

/**
 * The viewer needs WebGL and blob workers for the Draco decoder, which is why
 * worker-src and wasm-unsafe-eval appear. Everything else is locked to self;
 * the only outbound connection is the same-origin /api/tutor proxy.
 */
const dev = process.env.NODE_ENV === "development";

const CSP = [
  "default-src 'self'",
  // Next injects inline bootstrap scripts and the theme script runs inline.
  // 'unsafe-eval' is only for the dev server's hot reloader; production ships
  // without it. 'wasm-unsafe-eval' is required by the Draco decoder.
  `script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval'${dev ? " 'unsafe-eval'" : ""}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  `connect-src 'self'${dev ? " ws: http://localhost:*" : ""}`,
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  ...(dev ? [] : ["upgrade-insecure-requests"]),
].join("; ");

const SECURITY_HEADERS = [
  { key: "Content-Security-Policy", value: CSP },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "X-Frame-Options", value: "DENY" },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=(), interest-cohort=()",
  },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  compress: true,

  headers: async () => [
    {
      source: "/:path*",
      headers: SECURITY_HEADERS,
    },
    {
      // Model packs are regenerated by scripts/split-by-system.mjs, so they
      // are versioned by content rather than by filename. A long max-age with
      // revalidation gets the caching win without stranding users on stale
      // geometry after a re-ingest.
      source: "/models/:path*",
      headers: [
        {
          key: "Cache-Control",
          value: "public, max-age=604800, stale-while-revalidate=86400",
        },
      ],
    },
    {
      source: "/slices/:path*",
      headers: [
        {
          key: "Cache-Control",
          value: "public, max-age=604800, stale-while-revalidate=86400",
        },
      ],
    },
    {
      source: "/draco/:path*",
      headers: [
        { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
      ],
    },
    {
      // A stale worker would pin users to an old caching strategy.
      source: "/sw.js",
      headers: [{ key: "Cache-Control", value: "no-cache, no-store, must-revalidate" }],
    },
  ],
};

export default nextConfig;
